name: ChatDefender
main: falkirks\chatdefender\ChatDefender
version: 1.1.1
author: Falkirks
api: [1.6.0]
load: POSTWORLD
permissions:
 chatdefender:
  default: op
  description: ChatDefender top level
  children:
   chatdefender.exempt:
    default: op
    description: Exempt from all blocks
    children:
      chatdefender.exempt.similar:
        default: op
        description: Exempt from similarity checking
      chatdefender.exempt.rate:
        default: op
        description: Exempt from rate limit
